project:
  type: book
  output-dir: docs

book:
  google-analytics: "G-N2T5TFNFY7"
  title: "Statistics for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: 12/25/2025
  chapters:
    - index.qmd
    - prob.qmd
    - bayes.qmd
    - distr-shape.qmd
    - distr-d.qmd
    - distr-c.qmd
    - thanks.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - zephyr
      - brand

comments:
  giscus:
    repo: thinhong/s4bvn
    repo-id: R_kgDOQtVYcQ

